"""initial migration

Revision ID: 58298723b247
Revises: 
Create Date: 2024-11-24 15:47:21.407320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58298723b247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_control',
    sa.Column('discord_server_id', sa.String(length=20), nullable=False),
    sa.Column('discord_channel_ids', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('discord_server_id')
    )
    op.create_table('channel_message_traffic',
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('eth_place_bots', sa.Integer(), nullable=True),
    sa.Column('count_thread', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time_stamp')
    )
    op.create_table('config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('message_delete_tracker',
    sa.Column('discord_message_id', sa.String(length=20), nullable=False),
    sa.Column('discord_server_id', sa.String(length=20), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=20), nullable=True),
    sa.Column('time_to_delete', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('discord_message_id')
    )
    op.create_table('place_projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pixels_drawn', sa.Integer(), nullable=True),
    sa.Column('discord_user_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('place_throughput_log',
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('message_batch_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time_stamp')
    )
    op.create_table('users',
    sa.Column('discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('discord_user_id')
    )
    op.create_table('place_pixels',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('x_coordinate', sa.Integer(), nullable=False),
    sa.Column('y_coordinate', sa.Integer(), nullable=False),
    sa.Column('image_color', sa.String(length=6), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('place_color', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['place_projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_pixels')
    op.drop_table('users')
    op.drop_table('place_throughput_log')
    op.drop_table('place_projects')
    op.drop_table('message_delete_tracker')
    op.drop_table('config')
    op.drop_table('channel_message_traffic')
    op.drop_table('access_pontrol')
    # ### end Alembic commands ###
