version: 2
updates:
  - package-ecosystem: gradle
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      gradle-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: "net.dv8tion:JDA"
    commit-message:
      prefix: "gradle"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
