version: 2
updates:
  - package-ecosystem: maven
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      maven-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: "net.dv8tion:JDA"
    commit-message:
      prefix: "mvn"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
