services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: rd_bot
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: RubberDucky
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rd_bot -d RubberDucky" ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s

  alembic:
    extends:
      file: postgres/compose.yml
      service: alembic
    environment:
      DATABASE_URL: postgresql://rd_bot:password1234@postgres:5432/RubberDucky
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rubber_ducky
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/RubberDucky
      POSTGRES_USER: rd_bot
      POSTGRES_PASSWORD: password1234
    depends_on:
      postgres:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully

volumes:
  pg-data: