name: Build and Deploy the new Docker Images

on:
  push:
    branches: [ master, fix_deployment ]
#    paths:
#      - 'src/**'
#      - 'postgres/**'

jobs: 
  build_alembic:
    name: Building alembic Docker Image
#    if: ${{ contains(github.event.head_commit.message, 'postgres/') || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/build_alembic.yml
    secrets: inherit

  build_bot:
    name: Building Bot Docker Image
    uses: ./.github/workflows/build_alembic.yml
    secrets: inherit

  deploy:
    name: Deploying the new Docker Images
    needs: [build_alembic, build_bot]
#    if: always()
    uses: ./.github/workflows/notify_watchtower.yml
    