name: Build and Deploy the new Docker Images

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'postgres/**'

jobs: 
  build_alembic:
    name: Building alembic Docker Image
    if: >
      ${{ github.event_name == 'push' && github.event.commits.some(commit => commit.modified.includes('postgres/')) }}
    uses: ./.github/workflows/build_alembic.yml
    secrets: inherit

  build_bot:
    name: Building Bot Docker Image
    uses: ./.github/workflows/build_alembic.yml
    secrets: inherit

  deploy:
    name: Deploying the new Docker Images
    needs: [build_alembic, build_bot]
    if: always()
    uses: ./.github/workflows/notify_watchtower.yml
    secrets: inherit
