name: GitHub RubberDucky

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch on GitHub
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
        
      - name: Build Maven Project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          
      - name: Move old RubberDucky.jar to a save place
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: mkdir --parents ${{ secrets.TARGET_DIRECTORY }}/oldVersions/$(date +%Y%m%d_%H%M%S) && mv ${{ secrets.TARGET_DIRECTORY }}/RubberDucky.jar $_
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Deploy RubberDucky.jar to server
        uses: garygrossgarten/github-action-scp@release
        with:
          atomicPut: true    
          local: staging/RubberDucky-jar-with-dependencies.jar
          remote: ${{ secrets.TARGET_DIRECTORY }}/RubberDucky.jar
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Restart the RubberDucky service
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl restart RubberDucky
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
